-- Pas de séquence avec le SGBDR MYSQL
-- 1. Séquence sur toute les tables
-- SEQ Table CATEGORIE
CREATE SEQUENCE SEQ_CATEGORIE
START WITH 9
INCREMENT BY 1;
-- PostgreSQL
ALTER TABLE CATEGORIES
ALTER COLUMN code_categorie SET DEFAULT nextval('SEQ_CATEGORIE');
-- ORACLE
ALTER TABLE CATEGORIES MODIFY CODE_CATEGORIE DEFAULT SEQ_CATEGORIE.NEXTVAL;
-- MariaDB
ALTER TABLE CATEGORIES ALTER COLUMN CODE_CATEGORIE SET DEFAULT NEXT VALUE FOR SEQ_CATEGORIE;
-- SQL Server
ALTER TABLE CATEGORIES ADD DEFAULT NEXT VALUE FOR SEQ_CATEGORIE FOR CODE_CATEGORIE;

-- SEQ Table COMMANDE
CREATE SEQUENCE SEQ_COMMANDE
START WITH 830
INCREMENT BY 1;
-- PostgreSQL
ALTER TABLE COMMANDES
ALTER COLUMN NO_COMMANDE SET DEFAULT nextval('SEQ_COMMANDE');
-- ORACLE
ALTER TABLE COMMANDES MODIFY NO_COMMANDE DEFAULT SEQ_COMMANDE.NEXTVAL;
-- MariaDB
ALTER TABLE COMMANDES ALTER COLUMN NO_COMMANDE SET DEFAULT NEXT VALUE FOR SEQ_COMMANDEE;
-- SQL Server
ALTER TABLE COMMANDES ADD DEFAULT NEXT VALUE FOR SEQ_COMMANDE FOR NO_COMMANDE;

-- SEQ Table EMPLOYE
CREATE SEQUENCE SEQ_EMPLOYE
START WITH 10
INCREMENT BY 1;
-- PostgreSQL
ALTER TABLE EMPLOYES
ALTER COLUMN NO_EMPLOYE SET DEFAULT nextval('SEQ_EMPLOYE');
-- ORACLE
ALTER TABLE EMPLOYES MODIFY NO_EMPLOYE DEFAULT SEQ_EMPLOYE.NEXTVAL;
-- MariaDB
ALTER TABLE EMPLOYES ALTER COLUMN NO_EMPLOYE SET DEFAULT NEXT VALUE FOR SEQ_EMPLOYE;
-- SQL Server
ALTER TABLE EMPLOYES ADD DEFAULT NEXT VALUE FOR SEQ_EMPLOYE FOR NO_EMPLOYE;

-- SEQ Table FOURNISSEUR
CREATE SEQUENCE SEQ_FOURNISSEUR
START WITH 30
INCREMENT BY 1;
-- PostgreSQL
ALTER TABLE CATEGORIES
ALTER COLUMN NO_FOURNISSEUR SET DEFAULT nextval('SEQ_CATEGORIE');
-- ORACLE
ALTER TABLE CATEGORIES MODIFY NO_FOURNISSEUR DEFAULT SEQ_CATEGORIE.NEXTVAL;
-- MariaDB
ALTER TABLE CATEGORIES ALTER COLUMN NO_FOURNISSEUR SET DEFAULT NEXT VALUE FOR SEQ_CATEGORIE;
-- SQL Server
ALTER TABLE CATEGORIES ADD DEFAULT NEXT VALUE FOR SEQ_CATEGORIE FOR NO_FOURNISSEUR;

-- SEQ Table PRODUIT
CREATE SEQUENCE SEQ_PRODUIT
START WITH 78
INCREMENT BY 1;
-- PostgreSQL
ALTER TABLE CATEGORIES
ALTER COLUMN REF_PRODUIT SET DEFAULT nextval('SEQ_CATEGORIE');
-- ORACLE
ALTER TABLE CATEGORIES MODIFY REF_PRODUIT DEFAULT SEQ_CATEGORIE.NEXTVAL;
-- MariaDB
ALTER TABLE CATEGORIES ALTER COLUMN REF_PRODUIT SET DEFAULT NEXT VALUE FOR SEQ_CATEGORIE;
-- SQL Server
ALTER TABLE CATEGORIES ADD DEFAULT NEXT VALUE FOR SEQ_CATEGORIE FOR REF_PRODUIT;

-- 2. Nouvelles tables CLIENTS_V2 et FOURNISSEURS_V2 à partir des tables CLIENTS et FOURNISSEURS
CREATE TABLE CLIENTS_V2 AS
SELECT societe, adresse, ville, code_postal, pays, telephone, fax
FROM CLIENTS;
CREATE TABLE FOURNISSEURS_V2 AS
SELECT societe, adresse, ville, code_postal, pays, telephone, fax
FROM FOURNISSEURS;

-- 3. Séquence commune entre CLIENTS_V2 et FOURNISSEURS_V2
CREATE SEQUENCE SEQ_PARTENAIRE
START WITH 1
INCREMENT BY 1;
-- Les modifications de la structure selon les SGBDR
-- PostgreSQL
ALTER TABLE FOURNISSEURS_V2
ADD COLUMN no_fournisseur INT PRIMARY KEY
DEFAULT nextval('SEQ_PARTENAIRE');
ALTER TABLE CLIENTS_V2
ADD COLUMN code_client INT PRIMARY KEY
DEFAULT nextval('SEQ_PARTENAIRE');
--  SQL SERVER
ALTER TABLE FOURNISSEURS_V2 ADD 
  NO_FOURNISSEUR int DEFAULT NEXT VALUE FOR SEQ_PARTENAIRE,
  PRIMARY KEY (NO_FOURNISSEUR)
;
ALTER TABLE CLIENTS_V2 ADD 
  CODE_CLIENT int DEFAULT NEXT VALUE FOR SEQ_PARTENAIRE,
  PRIMARY KEY (CODE_CLIENT)
;
-- ORACLE
ALTER TABLE FOURNISSEURS_V2 ADD (
  NO_FOURNISSEUR number(10) DEFAULT SEQ_PARTENAIRE.NEXTVAL,
  PRIMARY KEY (NO_FOURNISSEUR)
);
ALTER TABLE CLIENTS_V2 ADD (
  CODE_CLIENT number(10) DEFAULT SEQ_PARTENAIRE.NEXTVAL,
  PRIMARY KEY (CODE_CLIENT)
);
-- MariaDB
ALTER TABLE FOURNISSEURS_V2 ADD NO_FOURNISSEUR int DEFAULT NEXT VALUE FOR SEQ_PARTENAIRE,
ADD PRIMARY KEY (NO_FOURNISSEUR);
ALTER TABLE CLIENTS_V2 ADD CODE_CLIENT int DEFAULT NEXT VALUE FOR SEQ_PARTENAIRE,
ADD PRIMARY KEY (CODE_CLIENT);